<?xml version="1.0" encoding="utf-8"?><Database Name="Locker" Class="MyShop1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=2RHJJ;Initial Catalog=Locker;Integrated Security=True" SettingsObjectName="MyShop1.DAL.Properties.Settings" SettingsPropertyName="LockerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.快递员表" Member="快递员表">
    <Type Name="快递员表">
      <Column Name="快递员ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="快递员姓名" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="联系电话" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="快递公司" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.日志表" Member="日志表">
    <Type Name="日志表">
      <Column Name="log_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="创建时间" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="操作内容" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.用户表" Member="用户表">
    <Type Name="用户表">
      <Column Name="CustomerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="手机号码" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="地址" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.快递柜表" Member="快递柜表">
    <Type Name="快递柜表">
      <Column Name="智能柜ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="智能柜类型" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="智能柜规格" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.寄件信息表" Member="寄件信息表">
    <Type Name="寄件信息表">
      <Column Name="预约ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="用户名" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="手机号码" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="寄件地址" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="智能柜类型" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="物品类型" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="预约日期" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.快递信息表" Member="快递信息表">
    <Type Name="快递信息表">
      <Column Name="快递单号" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="快递员姓名" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="快递员手机号码" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="用户手机号码" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="智能柜类型" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="存放时间" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.快递物流信息" Member="快递物流信息">
    <Type Name="快递物流信息">
      <Column Name="快递单号" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="收货人" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="收货地址" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="寄件人" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="发货地址" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="物流信息" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.投放快递审核表" Member="投放快递审核表">
    <Type Name="投放快递审核表">
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="快递单号" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="快递员姓名" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="快递员手机号码" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="用户手机号码" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="智能柜类型" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="存放时间" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.寄件信息审核表" Member="寄件信息审核表">
    <Type Name="寄件信息审核表">
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="用户名" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="手机号码" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="寄件地址" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="智能柜类型" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="物品类型" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="预约日期" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.快递滞留表" Member="快递滞留表">
    <Type Name="快递滞留表">
      <Column Name="快递单号" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="用户名" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="用户手机号码" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="滞留时长" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="超时费用" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.寄件订单信息表" Member="寄件订单信息表">
    <Type Name="寄件订单信息表">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="用户名" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="寄件码" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="智能柜ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.取件订单信息表" Member="取件订单信息表">
    <Type Name="取件订单信息表">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="用户名" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="取件码" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="智能柜ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="存放码" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>