#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 点餐管理系统
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="seles")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCartItem(CartItem instance);
    partial void UpdateCartItem(CartItem instance);
    partial void DeleteCartItem(CartItem instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::点餐管理系统.Properties.Settings.Default.selesConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CartItem> CartItem
		{
			get
			{
				return this.GetTable<CartItem>();
			}
		}
		
		public System.Data.Linq.Table<Dishes> Dishes
		{
			get
			{
				return this.GetTable<Dishes>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CartItem")]
	public partial class CartItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CartItemId;
		
		private int _Customers_id;
		
		private int _Dishes_ID;
		
		private string _Dishes_Name;
		
		private System.Nullable<decimal> _Unit_Price;
		
		private System.Nullable<decimal> _list_Price;
		
		private int _Qty;
		
		private int _Sales;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCartItemIdChanging(int value);
    partial void OnCartItemIdChanged();
    partial void OnCustomers_idChanging(int value);
    partial void OnCustomers_idChanged();
    partial void OnDishes_IDChanging(int value);
    partial void OnDishes_IDChanged();
    partial void OnDishes_NameChanging(string value);
    partial void OnDishes_NameChanged();
    partial void OnUnit_PriceChanging(System.Nullable<decimal> value);
    partial void OnUnit_PriceChanged();
    partial void Onlist_PriceChanging(System.Nullable<decimal> value);
    partial void Onlist_PriceChanged();
    partial void OnQtyChanging(int value);
    partial void OnQtyChanged();
    partial void OnSalesChanging(int value);
    partial void OnSalesChanged();
    #endregion
		
		public CartItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CartItemId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CartItemId
		{
			get
			{
				return this._CartItemId;
			}
			set
			{
				if ((this._CartItemId != value))
				{
					this.OnCartItemIdChanging(value);
					this.SendPropertyChanging();
					this._CartItemId = value;
					this.SendPropertyChanged("CartItemId");
					this.OnCartItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customers_id", DbType="Int NOT NULL")]
		public int Customers_id
		{
			get
			{
				return this._Customers_id;
			}
			set
			{
				if ((this._Customers_id != value))
				{
					this.OnCustomers_idChanging(value);
					this.SendPropertyChanging();
					this._Customers_id = value;
					this.SendPropertyChanged("Customers_id");
					this.OnCustomers_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dishes_ID", DbType="Int NOT NULL")]
		public int Dishes_ID
		{
			get
			{
				return this._Dishes_ID;
			}
			set
			{
				if ((this._Dishes_ID != value))
				{
					this.OnDishes_IDChanging(value);
					this.SendPropertyChanging();
					this._Dishes_ID = value;
					this.SendPropertyChanged("Dishes_ID");
					this.OnDishes_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dishes_Name", DbType="NVarChar(50)")]
		public string Dishes_Name
		{
			get
			{
				return this._Dishes_Name;
			}
			set
			{
				if ((this._Dishes_Name != value))
				{
					this.OnDishes_NameChanging(value);
					this.SendPropertyChanging();
					this._Dishes_Name = value;
					this.SendPropertyChanged("Dishes_Name");
					this.OnDishes_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Unit_Price
		{
			get
			{
				return this._Unit_Price;
			}
			set
			{
				if ((this._Unit_Price != value))
				{
					this.OnUnit_PriceChanging(value);
					this.SendPropertyChanging();
					this._Unit_Price = value;
					this.SendPropertyChanged("Unit_Price");
					this.OnUnit_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_list_Price", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> list_Price
		{
			get
			{
				return this._list_Price;
			}
			set
			{
				if ((this._list_Price != value))
				{
					this.Onlist_PriceChanging(value);
					this.SendPropertyChanging();
					this._list_Price = value;
					this.SendPropertyChanged("list_Price");
					this.Onlist_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int NOT NULL")]
		public int Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this.OnQtyChanging(value);
					this.SendPropertyChanging();
					this._Qty = value;
					this.SendPropertyChanged("Qty");
					this.OnQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sales", DbType="Int NOT NULL")]
		public int Sales
		{
			get
			{
				return this._Sales;
			}
			set
			{
				if ((this._Sales != value))
				{
					this.OnSalesChanging(value);
					this.SendPropertyChanging();
					this._Sales = value;
					this.SendPropertyChanged("Sales");
					this.OnSalesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dishes")]
	public partial class Dishes
	{
		
		private int _Dishes_ID;
		
		private string _Dishes_Name;
		
		private int _Classification_ID;
		
		private decimal _Unit_Price;
		
		private string _tasteName;
		
		private int _Sales;
		
		private string _Descn;
		
		private string _image;
		
		private decimal _list_Price;
		
		private int _Qty;
		
		public Dishes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dishes_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Dishes_ID
		{
			get
			{
				return this._Dishes_ID;
			}
			set
			{
				if ((this._Dishes_ID != value))
				{
					this._Dishes_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dishes_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Dishes_Name
		{
			get
			{
				return this._Dishes_Name;
			}
			set
			{
				if ((this._Dishes_Name != value))
				{
					this._Dishes_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Classification_ID", DbType="Int NOT NULL")]
		public int Classification_ID
		{
			get
			{
				return this._Classification_ID;
			}
			set
			{
				if ((this._Classification_ID != value))
				{
					this._Classification_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Price", DbType="Decimal(18,0) NOT NULL")]
		public decimal Unit_Price
		{
			get
			{
				return this._Unit_Price;
			}
			set
			{
				if ((this._Unit_Price != value))
				{
					this._Unit_Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasteName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tasteName
		{
			get
			{
				return this._tasteName;
			}
			set
			{
				if ((this._tasteName != value))
				{
					this._tasteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sales", DbType="Int NOT NULL")]
		public int Sales
		{
			get
			{
				return this._Sales;
			}
			set
			{
				if ((this._Sales != value))
				{
					this._Sales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descn", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Descn
		{
			get
			{
				return this._Descn;
			}
			set
			{
				if ((this._Descn != value))
				{
					this._Descn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this._image = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_list_Price", DbType="Decimal(18,0) NOT NULL")]
		public decimal list_Price
		{
			get
			{
				return this._list_Price;
			}
			set
			{
				if ((this._list_Price != value))
				{
					this._list_Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int NOT NULL")]
		public int Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this._Qty = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
